protocol/nft-website

docs/.vuepress/config.js
docs/.vuepress/theme/components/BackToTop.vue
docs/.vuepress/theme/components/Page.vue
docs/.vuepress/theme/styles/layout-center.styl

Partially addresses https://github.com/protocol/nft-website/issues/5

Add Custom BackToTop component

---

docs/.vuepress/config.js
docs/README.md

Minor social card tweaks to prepare for testing https://github.com/protocol/nft-website/issues/18

Minor social card tweaks

---

docs/.vuepress/head.js

Somehow the FPO fonts got reverted back instead of the pixel ones. Fixing.

fix: replace pixel fonts

---

docs/README.md

Here's a first pass at some front page content - I started to add more background info, but I think that probably belongs in the NFT Basics concept article instead. I'm working on that next and hope to have a draft up in a few hours.
closes #46

content: front page

---

docs/concepts/blockchains.md
docs/concepts/content-addressing.md
docs/concepts/content-persistence.md
docs/concepts/distributed-web.md
docs/concepts/non-fungible-tokens.md
docs/how-to/auditing-nfts.md
docs/how-to/managing-nfts.md
docs/reference/example-apps-code-samples.md
docs/reference/featured-sites.md
docs/reference/metadata-schemas.md
docs/reference/nft-marketplaces.md
docs/reference/recommended-tools.md
docs/tutorial/end-to-end-experience.md
docs/tutorial/first-steps.md
docs/tutorial/gallery-app.md
docs/tutorial/minting-app.md
docs/tutorial/using-nfts-in-games.md

Adds emoji indicator for "under construction" items in the nav.

feat: emoji for "under construction" items in nav

---

docs/.vuepress/theme/styles/alert-panels.styl
docs/concepts/non-fungible-tokens.md

This isn't quite finished, but it's a decent start, I think. I'll try to wrap it up tomorrow morning and send up a flare for reviews.
closes #20

content: nft basics

---

docs/concepts/non-fungible-tokens.md
docs/tutorial/first-steps.md

Updates `concepts/non-fungible-tokens.md` and `tutorial/first-steps.md` to appease the filecorgi.
Also updates`tutorial/first-steps.md` for copy and consistency edits.

feat: general copy edits

---

docs/concepts/content-addressing.md

This PR introduces minor copy and clarity edits, plus feeds the filecorgi some kibble to keep it happy.

feat: copy edits on content addressing concept guide

---

docs/.vuepress/config.js
docs/.vuepress/theme/styles/header.styl
docs/.vuepress/theme/styles/theme-dark.styl

feat: add algolia config

---

docs/reference/recommended-tools.md

With reference to ISSUE-32, recommended tools README is updated. Suggestions are welcomed !!

ISSUE-32 Recommended tools added

---

docs/reference/recommended-tools.md

In this PR:
- Makes edits to remove "under construction" details (construction sign, feedback box at bottom)
- Copy edits, fix a few broken links
- Add introductory text, section header text, call to contribute
Closes https://github.com/protocol/nft-website/pull/32 in conjunction with the work @pranshurastogi did in https://github.com/protocol/nft-website/pull/89 😊

Fix: Remove "under construction" details from Recommended Tools, add scaffolding

---

docs/reference/nft-marketplaces.md

Adds KodaDot to NFT Marketplaces page (see https://github.com/protocol/nft-website/issues/45#issuecomment-860633790) and alphabetizes all link lists.

content: add KodaDot, alphabetize links

---

docs/.vuepress/theme/components/EditOrIssue.vue
docs/.vuepress/theme/components/Page.vue
docs/.vuepress/theme/components/PageEdit.vue

This PR adds extra text to the last updated timestamp by ejecting the [`PageEdit` component](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/PageEdit.vue).
Closes #90

feat: add by suffix to last updated timestamp

---

docs/concepts/blockchains.md
docs/concepts/distributed-web.md
docs/how-to/creating-nfts.md
docs/reference/example-apps-code-samples.md
docs/reference/featured-sites.md
docs/tutorial/gallery-app.md
docs/tutorial/minting-app.md

sprinkle related links on wip pages

---

docs/reference/featured-sites.md

Resolves #33 
Open to any suggestions, otherwise this can be merged when approved.

Featured NFT dev sites

---

docs/reference/featured-sites.md
docs/reference/nft-marketplaces.md

Improve CTA (add your favorite marketplaces) content on the Marketplaces page.
Closes https://github.com/protocol/nft-website/issues/45.

content: improve CTA on marketplaces page

---

docs/how-to/lazy-minting.md
package-lock.json

Here's a draft of the lazy minting guide, which closes #97. I went ahead and merged the example into the nft-school-examples repo, so hopefully the links will resolve.
All copy edits and input is welcome 😄

content: add lazy minting guide

---

docs/.vuepress/config.js
docs/tutorial/minting-app.md

This a stab at our new high-level take on "building a minting app", to close #29.
@jessicaschilling this is pretty sparse, but probably better than nothing... I don't really think it's a "tutorial" per-se any more tho, so maybe it should be a "how to" instead? Feel free to move it if you think so :) And of course, tweak anything that needs tweaking.

content: minting app design

---

docs/.vuepress/theme/components/PageEdit.vue

fix: use edit link in last updated info

---

docs/tutorial/first-steps.md

Changing the way the output was written in the document to a "querySelector" using the method "textContent" in order to prevent XSS attacks.

Update - DOM

---

docs/tutorial/avax-nft.md

Kickstart the AVAX tutorial

---

docs/.vuepress/config.js
docs/guides/batch-minting.md
docs/tutorial/batch-minting.md

Kickstart batch-minting tutorial

---

docs/tutorial/mint-nftstorage-polygon.md

```bash
npx hardhat run scripts/mint-nft.mjs /--network PolygonMumbai
```
Bc of The slash the script did not work for me, so i fixed it.

Fixed a minor terminal script
